import type { NextApiRequest, NextApiResponse } from 'next';

export const drinks = [
  // Cà phê
  {
    id: 1,
    name: 'Cà phê đen',
    type: 'cà phê',
    price: 'rẻ',
    priceRange: '20-30k',
    time: ['sáng', 'trưa'],
    style: 'việt nam',
    tags: ['đậm đà', 'truyền thống'],
    description: 'Cà phê đen pha phin, vị đậm và thơm',
    image: 'ca-phe-den.jpg',
  },
  {
    id: 2,
    name: 'Cà phê sữa đá',
    type: 'cà phê',
    price: 'trung bình',
    priceRange: '25-35k',
    time: ['sáng', 'trưa'],
    style: 'việt nam',
    tags: ['ngọt', 'mát lạnh'],
    description: 'Cà phê sữa pha với sữa đặc và đá',
    image: 'ca-phe-sua-da.jpg',
  },
  {
    id: 3,
    name: 'Cà phê bạc sỉu',
    type: 'cà phê',
    price: 'trung bình',
    priceRange: '25-35k',
    time: ['sáng'],
    style: 'việt nam',
    tags: ['sữa', 'ngọt'],
    description: 'Cà phê ít, sữa nhiều, thơm mát',
    image: 'ca-phe-bac-siu.jpg',
  },
  {
    id: 4,
    name: 'Cà phê trứng',
    type: 'cà phê',
    price: 'cao',
    priceRange: '40-50k',
    time: ['sáng'],
    style: 'việt nam',
    tags: ['đặc biệt', 'béo'],
    description: 'Cà phê trứng thơm ngon, vị béo từ lòng đỏ trứng',
    image: 'ca-phe-trung.jpg',
  },
  {
    id: 5,
    name: 'Cà phê muối',
    type: 'cà phê',
    price: 'trung bình',
    priceRange: '30-40k',
    time: ['sáng'],
    style: 'việt nam',
    tags: ['đậm đà', 'đặc biệt'],
    description: 'Cà phê với chút muối, hương vị đặc biệt',
    image: 'ca-phe-muoi.jpg',
  },
  {
    id: 6,
    name: 'Cà phê espresso',
    type: 'cà phê',
    price: 'trung bình',
    priceRange: '25-35k',
    time: ['sáng'],
    style: 'italy',
    tags: ['đậm đà', 'cô đặc'],
    description: 'Espresso đậm đà, cô đặc với lớp crema',
    image: 'espresso.jpg',
  },
  {
    id: 7,
    name: 'Cà phê Cappuccino',
    type: 'cà phê',
    price: 'cao',
    priceRange: '40-50k',
    time: ['sáng', 'trưa'],
    style: 'italy',
    tags: ['béo', 'sữa'],
    description: 'Cappuccino mềm mịn, thơm sữa',
    image: 'cappuccino.jpg',
  },
  {
    id: 8,
    name: 'Cà phê Iced Americano',
    type: 'cà phê',
    price: 'trung bình',
    priceRange: '25-35k',
    time: ['sáng', 'trưa'],
    style: 'america',
    tags: ['đá', 'mát lạnh'],
    description: 'Americano với đá, mát lạnh',
    image: 'iced-americano.jpg',
  },
  {
    id: 9,
    name: 'Cà phê cốt dừa',
    type: 'cà phê',
    price: 'cao',
    priceRange: '35-45k',
    time: ['chiều'],
    style: 'việt nam',
    tags: ['béo', 'dừa'],
    description: 'Cà phê với hương vị cốt dừa thơm ngon',
    image: 'ca-phe-cot-dua.jpg',
  },
  {
    id: 10,
    name: 'Cà phê Latte',
    type: 'cà phê',
    price: 'cao',
    priceRange: '40-50k',
    time: ['sáng', 'chiều'],
    style: 'italy',
    tags: ['sữa', 'béo'],
    description: 'Latte với lớp bọt sữa mịn',
    image: 'latte.jpg',
  },
  {
    id: 11,
    name: 'Cà phê Mocha',
    type: 'cà phê',
    price: 'cao',
    priceRange: '40-55k',
    time: ['chiều'],
    style: 'italy',
    tags: ['sô cô la', 'béo'],
    description: 'Mocha với sô cô la và cà phê',
    image: 'mocha.jpg',
  },

  // Trà sữa
  {
    id: 12,
    name: 'Trà sữa trân châu trắng',
    type: 'trà sữa',
    price: 'trung bình',
    priceRange: '30-45k',
    time: ['trưa', 'chiều'],
    style: 'đài loan',
    tags: ['trân châu', 'mát lạnh'],
    description: 'Trà sữa trân châu trắng ngọt ngào',
    image: 'tra-sua-tran-chau-trang.jpg',
  },
  {
    id: 13,
    name: 'Trà sữa Oreo Cake Cream',
    type: 'trà sữa',
    price: 'cao',
    priceRange: '40-55k',
    time: ['chiều'],
    style: 'hiện đại',
    tags: ['ngọt', 'kem', 'bánh oreo'],
    description: 'Trà sữa Oreo kem béo và hương vị ngọt ngào',
    image: 'tra-sua-oreo.jpg',
  },
  {
    id: 14,
    name: 'Trà sữa trân châu đường đen',
    type: 'trà sữa',
    price: 'cao',
    priceRange: '35-50k',
    time: ['chiều'],
    style: 'đài loan',
    tags: ['ngọt', 'trân châu đường đen'],
    description: 'Trà sữa với trân châu đường đen, ngọt và thơm',
    image: 'tra-sua-tran-chau-duong-den.jpg',
  },
  {
    id: 15,
    name: 'Trà sữa khoai môn',
    type: 'trà sữa',
    price: 'trung bình',
    priceRange: '30-45k',
    time: ['trưa'],
    style: 'đài loan',
    tags: ['khoai môn', 'ngọt'],
    description: 'Trà sữa hương vị khoai môn, ngọt bùi',
    image: 'tra-sua-khoai-mon.jpg',
  },
  {
    id: 16,
    name: 'Trà sữa matcha đậu đỏ',
    type: 'trà sữa',
    price: 'cao',
    priceRange: '35-50k',
    time: ['chiều'],
    style: 'nhật bản',
    tags: ['matcha', 'đậu đỏ'],
    description: 'Trà sữa với matcha thơm ngon và đậu đỏ',
    image: 'tra-sua-matcha-dau-do.jpg',
  },
  {
    id: 17,
    name: 'Trà sữa sương sáo',
    type: 'trà sữa',
    price: 'trung bình',
    priceRange: '30-45k',
    time: ['chiều'],
    style: 'việt nam',
    tags: ['sương sáo', 'thanh mát'],
    description: 'Trà sữa với sương sáo mềm mịn',
    image: 'tra-sua-suong-sao.jpg',
  },
  {
    id: 18,
    name: 'Trà sữa hoa đậu biếc',
    type: 'trà sữa',
    price: 'cao',
    priceRange: '35-50k',
    time: ['chiều'],
    style: 'đài loan',
    tags: ['đậu biếc', 'đặc biệt'],
    description: 'Trà sữa với màu xanh từ hoa đậu biếc',
    image: 'tra-sua-hoa-dau-biec.jpg',
  },

  // Trà
  {
    id: 19,
    name: 'Trà hoa cúc',
    type: 'trà',
    price: 'trung bình',
    priceRange: '25-35k',
    time: ['chiều'],
    style: 'truyền thống',
    tags: ['thanh mát', 'hoa cúc'],
    description: 'Trà hoa cúc thanh mát, dễ chịu',
    image: 'tra-hoa-cuc.jpg',
  },
  {
    id: 20,
    name: 'Trà hoa đậu biếc',
    type: 'trà',
    price: 'trung bình',
    priceRange: '25-35k',
    time: ['chiều'],
    style: 'truyền thống',
    tags: ['đặc biệt', 'đậu biếc'],
    description: 'Trà đậu biếc màu xanh đẹp mắt',
    image: 'tra-hoa-dau-biec.jpg',
  },
  {
    id: 21,
    name: 'Trà hoa atiso',
    type: 'trà',
    price: 'trung bình',
    priceRange: '25-35k',
    time: ['sáng'],
    style: 'việt nam',
    tags: ['atiso', 'thanh mát'],
    description: 'Trà atiso đỏ thanh mát',
    image: 'tra-hoa-atiso.jpg',
  },
  {
    id: 22,
    name: 'Trà gừng',
    type: 'trà',
    price: 'trung bình',
    priceRange: '20-30k',
    time: ['sáng'],
    style: 'truyền thống',
    tags: ['ấm áp', 'gừng'],
    description: 'Trà gừng ấm áp',
    image: 'tra-gung.jpg',
  },
  {
    id: 23,
    name: 'Trà sen vàng',
    type: 'trà',
    price: 'trung bình',
    priceRange: '30-40k',
    time: ['chiều'],
    style: 'việt nam',
    tags: ['sen', 'thanh mát'],
    description: 'Trà sen vàng thơm mát',
    image: 'tra-sen-vang.jpg',
  },
  {
    id: 24,
    name: 'Trà cam thảo',
    type: 'trà',
    price: 'trung bình',
    priceRange: '20-30k',
    time: ['chiều'],
    style: 'truyền thống',
    tags: ['cam thảo', 'ngọt nhẹ'],
    description: 'Trà cam thảo ngọt nhẹ, dễ chịu',
    image: 'tra-cam-thao.jpg',
  },
  {
    id: 25,
    name: 'Trà la hán quả',
    type: 'trà',
    price: 'trung bình',
    priceRange: '25-35k',
    time: ['chiều'],
    style: 'truyền thống',
    tags: ['thanh nhiệt', 'la hán quả'],
    description: 'Trà la hán quả thanh mát',
    image: 'tra-la-han.jpg',
  },

  // Nước ép và sinh tố
  {
    id: 26,
    name: 'Sinh tố bơ',
    type: 'sinh tố',
    price: 'trung bình',
    priceRange: '30-45k',
    time: ['trưa'],
    style: 'việt nam',
    tags: ['béo', 'mát'],
    description: 'Sinh tố bơ thơm ngon, mịn màng',
    image: 'sinh-to-bo.jpg',
  },
  {
    id: 27,
    name: 'Sinh tố xoài',
    type: 'sinh tố',
    price: 'trung bình',
    priceRange: '30-45k',
    time: ['chiều'],
    style: 'việt nam',
    tags: ['ngọt', 'tươi'],
    description: 'Sinh tố xoài tươi mát, ngọt ngào',
    image: 'sinh-to-xoai.jpg',
  },
  {
    id: 28,
    name: 'Nước ép cam',
    type: 'nước ép',
    price: 'trung bình',
    priceRange: '25-35k',
    time: ['sáng'],
    style: 'việt nam',
    tags: ['vitamin C', 'mát'],
    description: 'Nước ép cam tươi mát, nhiều vitamin C',
    image: 'nuoc-ep-cam.jpg',
  },
  {
    id: 29,
    name: 'Nước ép thơm táo',
    type: 'nước ép',
    price: 'trung bình',
    priceRange: '30-45k',
    time: ['sáng'],
    style: 'việt nam',
    tags: ['ngọt', 'mát'],
    description: 'Nước ép từ thơm và táo, mát và ngọt',
    image: 'nuoc-ep-thom-tao.jpg',
  },
  {
    id: 30,
    name: 'Nước ép cà rốt',
    type: 'nước ép',
    price: 'trung bình',
    priceRange: '25-35k',
    time: ['sáng'],
    style: 'việt nam',
    tags: ['dinh dưỡng', 'vitamin A'],
    description: 'Nước ép cà rốt tốt cho sức khỏe',
    image: 'nuoc-ep-ca-rot.jpg',
  },
];

export const normalize = (text: string) => {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');
};

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'GET') {
    return res.status(405).json({ message: 'Method not allowed' });
  }

  const randomFood = drinks[Math.floor(Math.random() * drinks.length)];
  res.status(200).json(randomFood.name);
}
